import { getModel } from "../config/llmModels.js";
import { tavilyClient } from "../config/tavily.js";
import { deductCredits } from "../utils/deductCredits.js";
import { checkAgentLimit } from "../config/agentLimit.js";

const parseJsonResponse = (content) => {
    if (typeof content !== "string") return content;
    let clean = content.trim();
    if (clean.includes("```")) {
        const match = clean.match(/```(?:json)?\s*([\s\S]*?)\s*```/);
        if (match && match[1]) {
            clean = match[1].trim();
        }
    }
    const firstBrace = clean.indexOf("{");
    const lastBrace = clean.lastIndexOf("}");
    if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
        clean = clean.substring(firstBrace, lastBrace + 1);
    }
    try {
        return JSON.parse(clean);
    } catch (e) {
        return null;
    }
};

export const teamSwarmAgent = async (state) => {
    try {
        await checkAgentLimit(state.userId, "coding");
        const llm = await getModel("chat");
        const codeLlm = await getModel("coding");

        console.log("🚀 [Team Swarm] Starting Autonomous Multi-Agent Pipeline for:", state.prompt);

        // ==========================================
        // AGENT 1: Live Web Researcher
        // ==========================================
        let searchResults = [];
        try {
            if (tavilyClient) {
                const searchRes = await tavilyClient.search(state.prompt, {
                    searchDepth: "basic",
                    maxResults: 4
                });
                searchResults = searchRes.results || [];
            }
        } catch (searchErr) {
            console.warn("[Team Swarm] Tavily search skipped:", searchErr.message);
        }

        const researchSummary = searchResults.length > 0
            ? searchResults.map(r => `• **${r.title}**: ${r.content}`).join("\n")
            : "General internet domain knowledge applied.";

        // ==========================================
        // AGENT 2: Senior Architect & Coder
        // ==========================================
        const codePrompt = `You are CortexAI Lead Architect & Coder in a multi-agent swarm.

Goal: Build a modern, functional, responsive web application for:
User Request: ${state.prompt}

Research Context:
${researchSummary}

Design System:
- Dark theme or modern glassmorphism
- Responsive layout (Flexbox/Grid)
- Smooth interactions and micro-animations
- Beautiful typography and CSS variables
- Use real Unsplash images if needed (https://images.unsplash.com/...)

Return ONLY valid JSON:
{
  "projectTitle": "Title",
  "executiveSummary": "Brief overview of what was built and why",
  "files": [
    { "name": "index.html", "content": "..." },
    { "name": "style.css", "content": "..." },
    { "name": "script.js", "content": "..." }
  ]
}`;

        const codeRes = await codeLlm.invoke(codePrompt);
        const projectData = parseJsonResponse(codeRes.content) || {
            projectTitle: state.prompt,
            executiveSummary: "Multi-agent autonomous generation completed.",
            files: [
                {
                    name: "index.html",
                    content: `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>${state.prompt}</title><link rel="stylesheet" href="style.css"></head><body><main><h1>${state.prompt}</h1><p>Generated by CortexAI Autonomous Swarm.</p></main><script src="script.js"></script></body></html>`
                },
                {
                    name: "style.css",
                    content: `body { font-family: system-ui, sans-serif; background: #0f172a; color: #f8fafc; display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; }`
                },
                {
                    name: "script.js",
                    content: `console.log("CortexAI Autonomous Swarm Ready");`
                }
            ]
        };

        // ==========================================
        // AGENT 3: Technical Writer & Strategist
        // ==========================================
        const docPrompt = `You are CortexAI Executive Technical Writer.

Summarize the multi-agent collaboration results for:
"${state.prompt}"

Research gathered:
${researchSummary}

Include:
1. # 🤖 Autonomous Team Swarm Execution Report
2. ## 🔍 Research & Market Intelligence
3. ## 💻 Technical Architecture & Solution Delivered
4. ## 📊 Architecture Workflow (Include a Mermaid diagram: \`\`\`mermaid ... \`\`\`)
5. ## 🚀 Next Steps & Scalability

Keep it crisp, professional, and visually engaging in Markdown.`;

        const docRes = await llm.invoke(docPrompt);
        await deductCredits(state.userId, "coding");

        return {
            ...state,
            aiResponse: docRes.content,
            artifacts: [
                {
                    id: Date.now(),
                    type: "Project",
                    title: projectData.projectTitle || state.prompt,
                    files: projectData.files || []
                }
            ]
        };

    } catch (error) {
        console.error("Team Swarm error:", error);
        return {
            ...state,
            aiResponse: error?.data?.message || error?.message || "Failed to execute Team Swarm workflow",
            artifacts: []
        };
    }
};
