import PDFDocument from "pdfkit";

export const generatePdf = async (data) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "A4",
        margin: 50,
        bufferPages: true,
        info: {
          Author: "CortexAI",
          Title: data?.title || "Document",
          Creator: "CortexAI"
        }
      });

      const chunks = [];
      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => {
        try {
          resolve(Buffer.concat(chunks));
        } catch (err) {
          reject(err);
        }
      });
      doc.on("error", (err) => reject(err));

      const primaryColor = "#1e1b4b"; // Deep indigo
      const secondaryColor = "#475569"; // Slate gray
      const accentColor = "#4f46e5"; // Indigo accent
      const textColor = "#1f2937"; // Dark gray
      const lightBg = "#f8fafc"; // Very light slate

      // Document Title
      const title = data?.title || "Generated Document";
      doc
        .font("Helvetica-Bold")
        .fontSize(24)
        .fillColor(primaryColor)
        .text(title, { align: "left", lineGap: 4 });

      // Subtitle if available
      if (data?.subtitle) {
        doc.moveDown(0.3);
        doc
          .font("Helvetica")
          .fontSize(12)
          .fillColor(secondaryColor)
          .text(data.subtitle, { align: "left", lineGap: 3 });
      }

      // Metadata line (Date & Generated by)
      doc.moveDown(0.4);
      doc
        .font("Helvetica-Oblique")
        .fontSize(9)
        .fillColor("#94a3b8")
        .text(`Generated by CortexAI • ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })}`, { align: "left" });

      // Decorative divider line
      doc.moveDown(0.6);
      const startX = doc.page.margins.left;
      const contentWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
      doc
        .strokeColor(accentColor)
        .lineWidth(1.5)
        .moveTo(startX, doc.y)
        .lineTo(startX + contentWidth, doc.y)
        .stroke();

      doc.moveDown(1.2);

      // Render Sections
      const sections = Array.isArray(data?.sections) ? data.sections : [];

      if (sections.length === 0 && (data?.content || data?.text)) {
        // Fallback if data is a flat text or content
        const rawContent = data.content || data.text;
        doc
          .font("Helvetica")
          .fontSize(11)
          .fillColor(textColor)
          .text(String(rawContent), {
            align: "left",
            lineGap: 4
          });
      }

      sections.forEach((section, index) => {
        if (!section) return;

        // Check if page break is needed for heading to avoid orphans
        if (doc.y > doc.page.height - 120) {
          doc.addPage();
        }

        // Section Heading
        if (section.heading) {
          doc
            .font("Helvetica-Bold")
            .fontSize(14)
            .fillColor(primaryColor)
            .text(section.heading, { lineGap: 4 });

          doc.moveDown(0.3);
        }

        // Section Paragraph Content
        if (section.content) {
          doc.font("Helvetica").fontSize(11).fillColor(textColor);
          if (Array.isArray(section.content)) {
            section.content.forEach((para) => {
              doc.text(String(para), { align: "left", lineGap: 4 });
              doc.moveDown(0.4);
            });
          } else {
            doc.text(String(section.content), { align: "left", lineGap: 4 });
            doc.moveDown(0.4);
          }
        }

        // Section Items / Points (Bullet or Numbered)
        const items = section.items || section.points || [];
        if (Array.isArray(items) && items.length > 0) {
          const isNumbered =
            section.type === "numbered_list" ||
            section.type === "numbered" ||
            section.numbered === true ||
            (section.heading && /numbers?|step|sequence|count|rank|list/i.test(section.heading));

          items.forEach((item, itemIdx) => {
            const itemText = typeof item === "object" ? (item.text || item.title || JSON.stringify(item)) : String(item);
            
            // Format number or bullet
            const prefix = isNumbered ? `${itemIdx + 1}. ` : "• ";

            doc.font("Helvetica").fontSize(10.5).fillColor(textColor);

            doc.text(prefix + itemText, {
              indent: 12,
              lineGap: 3
            });
          });

          doc.moveDown(0.6);
        }

        // Section Code Block if any
        if (section.code) {
          doc.moveDown(0.3);
          const codeText = typeof section.code === "string" ? section.code : JSON.stringify(section.code, null, 2);
          
          doc
            .font("Courier")
            .fontSize(9.5)
            .fillColor("#0f172a")
            .text(codeText, {
              indent: 15,
              lineGap: 2
            });

          doc.moveDown(0.6);
        }

        // Table if any
        if (section.table && Array.isArray(section.table.rows)) {
          const headers = section.table.headers || [];
          const rows = section.table.rows || [];
          const colWidth = Math.floor(contentWidth / (headers.length || 1));

          if (headers.length > 0) {
            doc.font("Helvetica-Bold").fontSize(10).fillColor(primaryColor);
            headers.forEach((h, hIdx) => {
              doc.text(String(h), startX + hIdx * colWidth, doc.y, { width: colWidth - 10, continued: hIdx < headers.length - 1 });
            });
            doc.moveDown(0.5);
          }

          doc.font("Helvetica").fontSize(9.5).fillColor(textColor);
          rows.forEach((row) => {
            if (Array.isArray(row)) {
              row.forEach((cell, cIdx) => {
                doc.text(String(cell), startX + cIdx * colWidth, doc.y, { width: colWidth - 10, continued: cIdx < row.length - 1 });
              });
              doc.moveDown(0.4);
            }
          });
          doc.moveDown(0.6);
        }

        doc.moveDown(0.8);
      });

      // Add Page Numbers & Footer to all pages
      const range = doc.bufferedPageRange();
      for (let i = 0; i < range.count; i++) {
        doc.switchToPage(i);
        
        // Footer divider
        doc
          .strokeColor("#e2e8f0")
          .lineWidth(0.5)
          .moveTo(startX, doc.page.height - 40)
          .lineTo(startX + contentWidth, doc.page.height - 40)
          .stroke();

        // Footer text
        doc
          .font("Helvetica")
          .fontSize(8.5)
          .fillColor("#94a3b8")
          .text("Generated by CortexAI", startX, doc.page.height - 30, {
            align: "left",
            width: contentWidth / 2
          });

        doc
          .font("Helvetica")
          .fontSize(8.5)
          .fillColor("#94a3b8")
          .text(`Page ${i + 1} of ${range.count}`, startX + contentWidth / 2, doc.page.height - 30, {
            align: "right",
            width: contentWidth / 2
          });
      }

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};
