import { Check, Code2, Copy, Download, Eye, Maximize2, PanelRightClose, PanelRightOpen, RotateCcw, X } from 'lucide-react'
import React, { useEffect, useState } from 'react'
import { useSelector } from 'react-redux'
import { AnimatePresence, easeInOut, motion } from "motion/react"
import Editor from '@monaco-editor/react';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';

function Artifact() {
  const [collapsed, setCollapsed] = useState(false)
  const { artifacts } = useSelector(state => state.message)
  const [tab, setTab] = useState("code")
  const [activeFile, setActiveFile] = useState(0)
  const [copied, setCopied] = useState(false)
  const [mobileOpen, setMobileOpen] = useState(false)
  const [isZipping, setIsZipping] = useState(false)
  const [editableFiles, setEditableFiles] = useState([])

  // Keep local editable copy of files and ensure panel is expanded
  useEffect(() => {
    if (artifacts && artifacts.length > 0 && artifacts[0]?.files) {
      setEditableFiles(artifacts[0].files.map(f => ({ ...f })))
      setActiveFile(0)
      setCollapsed(false)
    }
  }, [artifacts])

  useEffect(() => {
    const handleOpen = () => {
      setCollapsed(false)
      setMobileOpen(true)
    }
    window.addEventListener('open-artifact-panel', handleOpen)
    return () => window.removeEventListener('open-artifact-panel', handleOpen)
  }, [])

  if (!artifacts || artifacts.length === 0) return null;

  const currentFile = editableFiles[activeFile] || artifacts[0]?.files?.[activeFile]
  const htmlFile = editableFiles.find(f => f.name === "index.html") || artifacts[0]?.files?.find(f => f.name === "index.html")
  const cssFile = editableFiles.find(f => f.name === "style.css") || artifacts[0]?.files?.find(f => f.name === "style.css")
  const jsFile = editableFiles.find(f => f.name === "script.js") || artifacts[0]?.files?.find(f => f.name === "script.js")

  const canPreview = Boolean(htmlFile)

  const previewDoc = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
     ${cssFile?.content || ""}
    </style>
</head>
<body>
 ${htmlFile?.content || ""} 
<script>
    ${jsFile?.content || ""}
</script>    
</body>
</html>`

  const handleCodeChange = (newVal) => {
    setEditableFiles(prev => {
      const updated = [...prev]
      if (updated[activeFile]) {
        updated[activeFile] = { ...updated[activeFile], content: newVal || "" }
      }
      return updated
    })
  }

  const handleResetCode = () => {
    if (artifacts[0]?.files) {
      setEditableFiles(artifacts[0].files.map(f => ({ ...f })))
    }
  }

  const handleCopy = async () => {
    await navigator.clipboard.writeText(currentFile?.content || "")
    setCopied(true)
    setTimeout(() => {
      setCopied(false)
    }, 2000)
  }

  const handleDownloadZip = async () => {
    try {
      setIsZipping(true)
      const zip = new JSZip()
      const filesToZip = editableFiles.length > 0 ? editableFiles : artifacts[0]?.files || []
      
      filesToZip.forEach(f => {
        zip.file(f.name, f.content || "")
      })

      // Add a README.md
      zip.file("README.md", `# ${artifacts[0]?.title || "CortexAI Project"}\n\nGenerated by CortexAI.\n\nOpen \`index.html\` in your browser to run this project.`)

      const blob = await zip.generateAsync({ type: "blob" })
      const safeTitle = (artifacts[0]?.title || "cortex-project")
        .toLowerCase()
        .replace(/[^a-z0-9]/g, "-")
        .slice(0, 30)
      saveAs(blob, `${safeTitle}.zip`)
    } catch (err) {
      console.error("ZIP download failed:", err)
    } finally {
      setIsZipping(false)
    }
  }

  const detectLanguage = (fileName = "") => {
    const name = fileName.toLowerCase()
    if (name.endsWith(".html")) return "html";
    if (name.endsWith(".css")) return "css";
    if (name.endsWith(".js") || name.endsWith(".jsx")) return "javascript";
    if (name.endsWith(".ts") || name.endsWith(".tsx")) return "typescript";
    if (name.endsWith(".json")) return "json";
    if (name.endsWith(".py")) return "python";
    if (name.endsWith(".java")) return "java";
    if (name.endsWith(".cpp") || name.endsWith(".c")) return "cpp";
    return "plaintext";
  }

  const PanelContent = ({ onClose }) => {
    return (
      <>
        {!collapsed ? (
          <div className='flex flex-col h-full bg-[#0d0f14]'>
            <div className='h-14 px-4 border-b border-white/[0.06] flex items-center justify-between gap-3 shrink-0'>
              <div className='flex items-center gap-2 flex-1 min-w-0'>
                <button
                  className='flex items-center justify-center w-7 h-7 rounded-lg text-slate-500 hover:text-slate-200 hover:bg-white/[0.05] transition-colors duration-150 bg-transparent border-none cursor-pointer shrink-0'
                  onClick={onClose ?? (() => setCollapsed(true))}
                  title="Close panel"
                >
                  {onClose ? <X size={15} /> : <PanelRightClose size={16} />}
                </button>
                <div className='flex items-center justify-center w-6 h-6 rounded-md bg-indigo-500/10 border border-indigo-500/20 shrink-0'>
                  <Code2 className="text-indigo-400" size={12} />
                </div>
                <div className='text-[13px] font-medium text-slate-200 truncate' title={artifacts[0]?.title}>
                  {artifacts[0]?.title}
                </div>
              </div>

              <div className='flex items-center gap-1.5 shrink-0'>
                {canPreview && (
                  <div className='flex items-center gap-1 bg-white/[0.04] border border-white/[0.06] p-1 rounded-lg mr-1'>
                    <button
                      onClick={() => setTab("code")}
                      className={`flex items-center gap-1 px-2 py-1 text-[11px] font-medium rounded-md transition-colors duration-150 cursor-pointer ${
                        tab === "code" ? "bg-indigo-500 text-white shadow-sm" : "text-slate-400 hover:text-slate-200"
                      }`}
                    >
                      <Code2 size={11} /> Code
                    </button>
                    <button
                      onClick={() => setTab("preview")}
                      className={`flex items-center gap-1 px-2 py-1 text-[11px] font-medium rounded-md transition-colors duration-150 cursor-pointer ${
                        tab === "preview" ? "bg-indigo-500 text-white shadow-sm" : "text-slate-400 hover:text-slate-200"
                      }`}
                    >
                      <Eye size={11} /> Preview
                    </button>
                  </div>
                )}

                <button
                  onClick={handleResetCode}
                  title="Reset to original code"
                  className='p-1.5 text-slate-400 hover:text-slate-200 hover:bg-white/[0.05] rounded-lg transition cursor-pointer'
                >
                  <RotateCcw size={14} />
                </button>

                <button
                  onClick={handleCopy}
                  title="Copy current file"
                  className='p-1.5 text-slate-400 hover:text-slate-200 hover:bg-white/[0.05] rounded-lg transition cursor-pointer'
                >
                  {copied ? <Check size={14} className="text-emerald-400" /> : <Copy size={14} />}
                </button>

                <button
                  onClick={handleDownloadZip}
                  disabled={isZipping}
                  title="Download Project as ZIP"
                  className='flex items-center gap-1 px-2.5 py-1 text-[11px] font-medium text-indigo-300 bg-indigo-500/10 hover:bg-indigo-500/20 border border-indigo-500/30 rounded-lg transition cursor-pointer'
                >
                  <Download size={12} />
                  <span>{isZipping ? 'Zipping...' : 'ZIP'}</span>
                </button>
              </div>
            </div>

            {tab === "code" && (
              <div className='flex h-auto border-b border-white/[0.06] overflow-x-auto [scrollbar-width:none] [&::-webkit-scrollbar]:hidden shrink-0 bg-[#111318]'>
                {editableFiles.map((f, index) => (
                  <button
                    key={index}
                    onClick={() => setActiveFile(index)}
                    className={`px-4 py-2 text-[11px] font-medium whitespace-nowrap transition-colors duration-150 border-r border-white/[0.05] relative cursor-pointer bg-transparent ${
                      activeFile === index ? "text-indigo-400 bg-white/[0.03]" : "text-slate-500 hover:text-slate-300"
                    }`}
                  >
                    {f?.name}
                    {activeFile === index && <div className='absolute bottom-0 left-0 right-0 h-[2px] bg-indigo-500 rounded-t-full' />}
                  </button>
                ))}
              </div>
            )}

            <div className='flex-1 overflow-hidden relative'>
              {tab === "preview" && canPreview ? (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ duration: 0.3 }}
                  className='w-full h-full'
                >
                  <iframe
                    title='preview'
                    srcDoc={previewDoc}
                    sandbox='allow-scripts allow-modals allow-same-origin'
                    className='w-full h-full bg-white'
                  />
                </motion.div>
              ) : (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ duration: 0.3 }}
                  className='w-full h-full'
                >
                  <Editor
                    theme='vs-dark'
                    language={detectLanguage(currentFile?.name)}
                    value={currentFile?.content || ""}
                    onChange={handleCodeChange}
                    options={{
                      readOnly: false,
                      minimap: { enabled: false },
                      fontSize: 13,
                      wordWrap: "on",
                      automaticLayout: true,
                      scrollBeyondLastLine: false,
                      padding: { top: 16 },
                      lineNumbers: "on",
                      renderLineHighlight: "all"
                    }}
                  />
                </motion.div>
              )}
            </div>
          </div>
        ) : (
          <div className='hidden lg:flex h-full border-l border-white/[0.06] bg-[#0d0f14] flex-col items-center py-4 gap-3 shrink-0'>
            <button
              className='flex items-center justify-center w-7 h-7 rounded-lg text-slate-500 hover:text-slate-200 hover:bg-white/[0.05] transition-colors duration-150 bg-transparent border-none cursor-pointer shrink-0'
              onClick={() => setCollapsed(false)}
            >
              <PanelRightOpen size={16} />
            </button>
            <div className='flex items-center gap-2 flex-1 min-w-0'>
              <div
                className='text-[10px] font-medium text-slate-600 tracking-widest uppercase whitespace-nowrap'
                style={{
                  writingMode: "vertical-lr",
                  transform: "rotate(180deg)"
                }}
              >
                {artifacts[0]?.title}
              </div>
            </div>
          </div>
        )}
      </>
    )
  }

  return (
    <>
      <button
        onClick={() => setMobileOpen(true)}
        className="lg:hidden fixed bottom-24 right-4 z-40 flex items-center gap-2 px-3.5 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-[12px] font-medium shadow-lg shadow-indigo-500/20 border-none cursor-pointer transition-colors duration-150"
      >
        <Code2 size={13} />
        View Sandbox
      </button>

      <AnimatePresence>
        {mobileOpen && (
          <>
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.2 }}
              onClick={() => setMobileOpen(false)}
              className="lg:hidden fixed inset-0 z-50 bg-black/60 backdrop-blur-sm"
            />
            <motion.div
              initial={{ x: "100%" }}
              animate={{ x: 0 }}
              exit={{ x: "100%" }}
              transition={{ duration: 0.25, ease: "easeInOut" }}
              className="lg:hidden fixed inset-y-0 right-0 z-50 w-[92vw] max-w-[480px] border-l border-white/[0.06] overflow-hidden"
            >
              <PanelContent onClose={() => setMobileOpen(false)} />
            </motion.div>
          </>
        )}
      </AnimatePresence>

      <motion.div
        initial={{ width: 440 }}
        animate={{ width: collapsed ? 48 : 440 }}
        transition={{
          duration: 0.25,
          ease: easeInOut
        }}
        className='hidden lg:flex h-full border-l border-white/[0.06] flex-col overflow-hidden shrink-0'
      >
        <PanelContent />
      </motion.div>
    </>
  )
}

export default Artifact;
